# Generated by Django 4.1.7 on 2023-04-21 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camion',
            fields=[
                ('matricula', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('modelo', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
                ('almacenamiento', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'departamento',
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('NIT', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'empresa',
            },
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ModAdmin.departamento')),
            ],
            options={
                'db_table': 'municipio',
            },
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(default='Colombia', max_length=100)),
            ],
            options={
                'db_table': 'pais',
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'rol',
            },
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=100)),
                ('estado', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ModAdmin.empresa')),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ModAdmin.municipio')),
            ],
            options={
                'db_table': 'sucursal',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('cedula', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('correo', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('estado', models.BooleanField(default=True)),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ModAdmin.rol')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ModAdmin.sucursal')),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
        migrations.CreateModel(
            name='Viaje',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.BooleanField(default=False)),
                ('inicio', models.CharField(max_length=100)),
                ('llegada', models.CharField(max_length=100)),
                ('fecha', models.DateTimeField()),
                ('camion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ModAdmin.camion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ModAdmin.usuario')),
            ],
            options={
                'db_table': 'viaje',
            },
        ),
        migrations.CreateModel(
            name='PuntoEntrega',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('direccion', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=100)),
                ('numero_lote_entrega', models.IntegerField()),
                ('estado', models.BooleanField(default=False)),
                ('viaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ModAdmin.viaje')),
            ],
            options={
                'db_table': 'puntoEntrega',
            },
        ),
        migrations.AddField(
            model_name='empresa',
            name='Pais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ModAdmin.pais'),
        ),
        migrations.CreateModel(
            name='DetalleViaje',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('direccion', models.CharField(max_length=100)),
                ('fecha', models.DateTimeField()),
                ('descripcion', models.CharField(max_length=500)),
                ('descanso', models.BooleanField(default=False)),
                ('viaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ModAdmin.viaje')),
            ],
            options={
                'db_table': 'detalleViaje',
            },
        ),
        migrations.AddField(
            model_name='departamento',
            name='pais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ModAdmin.pais'),
        ),
    ]
