# Generated by Django 4.1.7 on 2023-04-19 01:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'departamento',
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('NIT', models.IntegerField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'empresa',
            },
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=100)),
                ('Departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ModAdmin.departamento')),
            ],
            options={
                'db_table': 'municipio',
            },
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(default='Colombia', max_length=100)),
            ],
            options={
                'db_table': 'pais',
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'rol',
            },
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=100)),
                ('Direccion', models.CharField(max_length=100)),
                ('Departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ModAdmin.departamento')),
                ('Empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ModAdmin.empresa')),
                ('Municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ModAdmin.municipio')),
            ],
            options={
                'db_table': 'sucursal',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('Cedula', models.IntegerField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=100)),
                ('Apellido', models.CharField(max_length=100)),
                ('Correo', models.CharField(max_length=100)),
                ('Password', models.CharField(max_length=100)),
                ('Rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ModAdmin.rol')),
                ('Sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ModAdmin.sucursal')),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
        migrations.CreateModel(
            name='Viaje',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Estado', models.BooleanField(default=False)),
                ('Inicio', models.CharField(max_length=100)),
                ('Llegada', models.CharField(max_length=100)),
                ('Fecha', models.DateTimeField()),
                ('Placa_Camion', models.CharField(max_length=6)),
                ('Usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ModAdmin.usuario')),
            ],
            options={
                'db_table': 'viaje',
            },
        ),
        migrations.CreateModel(
            name='PuntoEntrega',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Direccion', models.CharField(max_length=100)),
                ('Nombre', models.CharField(max_length=100)),
                ('Numero_Lote_Entrega', models.IntegerField()),
                ('Estado', models.BooleanField(default=False)),
                ('Viaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ModAdmin.viaje')),
            ],
            options={
                'db_table': 'puntoEntrega',
            },
        ),
        migrations.AddField(
            model_name='empresa',
            name='Pais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ModAdmin.pais'),
        ),
        migrations.CreateModel(
            name='DetalleViaje',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Direccion', models.CharField(max_length=100)),
                ('Fecha', models.DateTimeField()),
                ('Descanso', models.BooleanField(default=False)),
                ('Viaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ModAdmin.viaje')),
            ],
            options={
                'db_table': 'detalleViaje',
            },
        ),
        migrations.AddField(
            model_name='departamento',
            name='Pais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ModAdmin.pais'),
        ),
    ]
