# Generated by Django 4.1.7 on 2023-04-28 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ModAdmin', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='camion',
            old_name='almacenamiento',
            new_name='capacidad',
        ),
        migrations.AlterField(
            model_name='departamento',
            name='pais',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='detalleviaje',
            name='viaje',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='pais',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='municipio',
            name='departamento',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='puntoentrega',
            name='viaje',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='empresa',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='municipio',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='sucursal',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='camion',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='usuario',
            field=models.CharField(max_length=100),
        ),
    ]
