# Generated by Django 4.1.7 on 2023-05-04 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ModAdmin', '0003_sucursal_departamento_usuario_empresa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sucursal',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
