# Generated by Django 4.1.7 on 2023-05-07 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ModAdmin', '0005_camion_empresa_camion_sucursal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viaje',
            name='llegada',
        ),
        migrations.AlterField(
            model_name='puntoentrega',
            name='viaje',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
