# Generated by Django 4.1.7 on 2023-05-12 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ModAdmin', '0006_remove_viaje_llegada_alter_puntoentrega_viaje'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puntoentrega',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
