# Generated by Django 4.1.7 on 2023-05-12 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ModAdmin', '0007_alter_puntoentrega_estado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='puntoentrega',
            old_name='numero_lote_entrega',
            new_name='peso',
        ),
    ]
