# Generated by Django 4.1.7 on 2023-05-18 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ModAdmin', '0008_rename_numero_lote_entrega_puntoentrega_peso'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mercancia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('peso', models.IntegerField()),
                ('estado', models.BooleanField(default=True)),
                ('carga', models.BooleanField(default=False)),
                ('descarga', models.BooleanField(default=False)),
                ('puntoEntrega', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'mercancia',
            },
        ),
        migrations.RemoveField(
            model_name='puntoentrega',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='puntoentrega',
            name='peso',
        ),
    ]
