# Generated by Django 4.1.7 on 2023-05-18 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ModAdmin', '0009_mercancia_remove_puntoentrega_nombre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mercancia',
            name='puntoEntrega',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
