# Generated by Django 4.1.7 on 2023-05-26 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ModAdmin', '0010_alter_mercancia_puntoentrega'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='empresa',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='sucursal',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
