# Generated by Django 4.1.7 on 2023-05-26 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ModAdmin', '0011_alter_usuario_empresa_alter_usuario_sucursal'),
    ]

    operations = [
        migrations.AddField(
            model_name='camion',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
