# Generated by Django 4.1.7 on 2023-05-27 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ModAdmin', '0012_camion_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='mercancia',
            name='empresa',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mercancia',
            name='sucursal',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='puntoentrega',
            name='empresa',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='puntoentrega',
            name='sucursal',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
