# Generated by Django 4.1.7 on 2023-05-27 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ModAdmin', '0014_alter_sucursal_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='viaje',
            name='empresa',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='viaje',
            name='sucursal',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
