# Generated by Django 4.1.7 on 2023-05-31 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ModAdmin', '0016_mercancia_correoremitente_mercancia_puntoinicio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mercancia',
            name='viaje',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
