# Generated by Django 4.1.7 on 2023-05-31 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ModAdmin', '0017_mercancia_viaje'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mercancia',
            old_name='correoRemitente',
            new_name='correoDestinatario',
        ),
        migrations.RenameField(
            model_name='mercancia',
            old_name='remitente',
            new_name='destinatario',
        ),
    ]
