# Generated by Django 4.1.7 on 2023-05-31 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ModAdmin', '0018_rename_correoremitente_mercancia_correodestinatario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mercancia',
            name='camion',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
