# Generated by Django 4.1.7 on 2023-05-31 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ModAdmin', '0019_mercancia_camion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mercancia',
            name='camion',
        ),
        migrations.RemoveField(
            model_name='mercancia',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='viaje',
            name='inicio',
        ),
    ]
