# Generated by Django 4.1.7 on 2023-06-02 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ModAdmin', '0022_mercancia_altura_mercancia_ancho_mercancia_largo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'estado',
            },
        ),
        migrations.AlterField(
            model_name='camion',
            name='estado',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='mercancia',
            name='estado',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='estado',
            field=models.CharField(max_length=100),
        ),
    ]
