# Generated by Django 4.1.7 on 2023-06-02 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ModAdmin', '0023_estado_alter_camion_estado_alter_mercancia_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mercancia',
            name='fechaCarga',
            field=models.DateTimeField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mercancia',
            name='fechaDescarga',
            field=models.DateTimeField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mercancia',
            name='telefonoDestinatario',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mercancia',
            name='telefonoRemitente',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
