# Generated by Django 4.1.7 on 2023-06-02 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ModAdmin', '0024_mercancia_fechacarga_mercancia_fechadescarga_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mercancia',
            name='fechaCarga',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='mercancia',
            name='fechaDescarga',
            field=models.DateTimeField(null=True),
        ),
    ]
