# Generated by Django 4.1.7 on 2023-06-03 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ModAdmin', '0025_alter_mercancia_fechacarga_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camion',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
