# Generated by Django 4.1.7 on 2023-06-03 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ModAdmin', '0026_alter_camion_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='disponibilidad',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
